### ISSUE TITLE
"Skip to newest posts" only available when the client is first launched

### ISSUE THREAD

**Issue by Fitzsimmons** [trunks-social/trunks-public#274]
I haven't been able to find a way to skip to the absolutely latest posts on my timeline unless I fully close and reopen the app, and then use the "skip to newest posts" toast that appears in the timeline. Is there another, persistent way in the interface to do this? If not, could you please add one?

**Comment by Decad3nce** [comment]
This is definitely something I've wanted to do. Thanks for filing this. I'll track it for the next release.

**Comment by mcmahanp** [comment]
This has been a persistent issue for me as well. I've gotten used to forcing the app to close and reopening it just to get to the newest posts. Subscribed to see if it gets resolved!

**Comment by Decad3nce** [comment]
@mcmahanp @Fitzsimmons would either of you prefer the different home feed mode? Name "Recent Mode"?

It'll always show you the newest posts whenever you enter the app.

I'm trying to understand if there's a discovery gap rather than a functionality gap.

I'll likely still implement a persistent mechanism to achieve this in "Remember Mode"

![Screenshot_20231023-073631.png](https://github.com/trunks-social/trunks-public/assets/315745/f110da16-9753-41aa-8a58-b1d7f2b7a347)

**Comment by mcmahanp** [comment]
Thanks for the followup, @Decad3nce 

I currently already use "Recent mode" (the leftmost icon in your screenshot). But still whenever I open the app it starts me where I last left off. If it's been a while since I opened the app, this is usually a long ways from what are actually the most recent posts. 

Tapping "home" scrolls me up to the top of what was already loaded and then loads some more recent posts, but not all. I can slowly get to the most recent post if it's been, say, 12 hours since I've used the app by repeating the "home" tap maybe 10-20 times, waiting between each tap for some more recent posts to load.

I'd personally be happy if simply tapping "home" while in the "Recent mode" just brought me all the way up to the latest post in my feed, rather than just the latest post already loaded.

Is there another setting that needs to be checked to make this work as expected? Or is this maybe a bug? Or something server-specific (I'm on mas.to)?

**Comment by Decad3nce** [comment]
@mcmahanp that is interesting, that seems like a bug, you should always be at the most recent post after opening the app except for if it's still cached in the background.

Few questions, do you use other apps or other sites to ingest Mastodon feeds?

What platform is that on?

**Comment by mcmahanp** [comment]
I'm on Android. Trunks is the only app I use there to access mastodon. On my computer I just use my instance's default website.

I suspect it may that the app is "cached in the background." On my phone, at least, exiting out of an app just hides it, and opening the app again just foregrounds it again. So it is in the same state as I left it. I think this is the standard behavior on Android. Only if I've not opened an app for a very long time (maybe a day?) or if I've opened up a lot of other apps that want those resources does Android actually close the app. This is why forcing the app to close and then reopening will at least give me the option to see newest posts with a small disappearing button at the top of the feed.

I expect there is some way to detect when a backgrounded app is opened again on Android. Or, as I mentioned before, I would personally find this to be a non-issue if tapping the 'home' button just brought me to the most recent posts.

**Comment by mcmahanp** [comment]
Great. Thanks so much!
